### ISSUE TITLE
OpenFlow1.3版 ラーニングスイッチの質問

### ISSUE THREAD

**Issue by yasuhito** [yasuhito/trema-book#105]
OpenFlow1.3版ラーニングスイッチ作者!! @shun159 さんいくつか教えてください:

- [x] **テーブルIDの振りかたの決まり?:**
いまの実装だとテーブルIDの0番と1番をぞれぞれ次のように振っています。質問ですが、OpenFlowの仕様とかあとはベストプラクティスみたいなもので、IDはこういう振りかたをしようとか、予約されていて使えないIDなどというものってあるでしょうか?

```ruby
  INGRESS_FILTERING_TABLE_ID = 0
  FORWARDING_TABLE_ID = 1
```

- [x] **802.1D予約済みスパニングツリーMACアドレス対応?:**
OpenFlow1.0版のラーニングスイッチでは、次のように `Mac#reserved?` メソッドで宛先が802.1D予約済みスパニングツリーMACアドレスなモノをdropしています。OpenFlow1.3版もフィルタリングテーブルでこうしたほうがいいですか? (関連イシュー #90)

```ruby
  def packet_in(_datapath_id, message)
    return if message.destination_mac.reserved?
```

- [ ] **Trema (OpenFlow1.3) の改善ポイント?:**
TremaのOpenFlow1.3で書いてて気持ち悪いところや改善できそうなことがあったら何でも教えてください。たとえば前に聞いたと思いますが、FlowModするときにマッチが不要なところでもいちいち `match: Match.new` と書かなければいけないのは直したほうがいい気がします。

```ruby
    send_flow_mod_add(
      datapath_id,
      table_id: FORWARDING_TABLE_ID,
      idle_timeout: 0,
      priority: 1,
      match: Match.new,
      instructions: Apply.new([SendOutPort.new(:controller),
                               SendOutPort.new(:flood)])
    )
```

**Comment by shun159** [comment]
取り急ぎですが…

> テーブルIDの振りかたの決まり?

決まりについては、私は特に見たことはありません。
ただし、ご存じのとおりですが、予約されているIDがあります。`ofptt_max`については、
利用できないと思います。`ofptt_all`については、resubmit_tableの時やflow_statsなどのようなときに利用できると思います。もし必要であれば、実行時のログをお出しします。
````ruby
ofptt_all = 0xff
ofptt_max = 0xfe
````

> 802.1D予約済みスパニングツリーMACアドレス対応?:

datapathでマルチキャストフレームをdropしているのであれば、packet_inとして上がってくることはないと思うので、そのガードは不要になるかと思います。そのフレームのsrc_mac学習にpacket_in必要かどうかは少し考えさせてください。

> Trema (OpenFlow1.3) の改善ポイント?: 気がついたらissue出しておきます！chatのものはまだ出来ていませんが、近々issueだします。時間かかってすみません。

**Comment by yasuhito** [comment]
テーブルIDの説明ありがとうございます。OFPTT_MAXまでの値の使い方はとくにコレというのは決まってなくて好きに使って良いんですね。ちなみにいまスペックを確認したら OFPTT_MAX は last usable table number とのことなので使っても良いみたいです。

**Comment by yasuhito** [comment]
ついでに、ためしに `Pio::GotoTable.new(0xfff)` してみたところ以下のようにエラーが出なかったので、こちらは Pio のチケットに入れておきます。`table_id` 値は uint8 なので 0xfff を入れても 255 に丸めてくれますが、`.new` で例外を投げたほうが良いと思っています。
```
$ irb -Ilib -rpio                                                                                                                       rvm:ruby-2.0.0-p598 
cannot load such file -- wirble
2.0.0 :001 > require 'pio/open_flow13'
 => false 
2.0.0 :002 > Pio::GotoTable.new(0xff)
 => #<Pio::GotoTable:0x007fcc84c23e88 @format={:instruction_type=>1, :instruction_length=>8, :table_id=>255}> 
2.0.0 :003 > Pio::GotoTable.new(0xfff)
 => #<Pio::GotoTable:0x007fcc8329d748 @format={:instruction_type=>1, :instruction_length=>8, :table_id=>255}>
```

**Comment by shun159** [comment]
あと、openvswitch-2.3.90の場合、OFPTT_MAXへflow_modすると、eperm/bad requestが報告されることにご注意ください。

**Comment by yasuhito** [comment]
> datapathでマルチキャストフレームをdropしているのであれば、packet_inとして上がってくることはないと思うので、そのガードは不要になるかと思います。そのフレームのsrc_mac学習にpacket_in必要かどうかは少し考えさせてください。

わかりました。なんとなくですが、そのマルチキャストフレームを出してる人も宛先になりうるので、packet_inでsrc_macを学習する必要がある気がします。

**Comment by yasuhito** [comment]
> あと、openvswitch-2.3.90の場合、OFPTT_MAXへflow_modすると、eperm/bad requestが報告されることにご注意ください。

マジですか! これは vswitch のバグだから、対処しなくていいかな。。。

**Comment by shun159** [comment]
> マジですか! これは vswitch のバグだから、対処しなくていいかな。。。

おっ、そうなのですか。lagopusとかはどうなんでしょう…。最近触ってないのでわからないですが。。。

> わかりました。なんとなくですが、そのマルチキャストフレームを出してる人も宛先になりうるので、packet_inでsrc_macを学習する必要がある気がします。

ですね。テーブルを少し整理してみます。

**Comment by yasuhito** [comment]
あと、いまのOpenFlow1.3ラーニングスイッチでは 01:00:5e:xx:xx:xx も drop してるのですが、これも src_mac を学習しないといけない気がします。

**Comment by shun159** [comment]
はい、そのとおりだと思います。
ちょっと絵とか簡単に書いて整理しようかとおもいます。

**Comment by yasuhito** [comment]
> おっ、そうなのですか。lagopusとかはどうなんでしょう…。最近触ってないのでわからないですが。。。

1.3.4 の仕様には OFPTT_MAX まで使ってよい、と書いてあるのでやはり vswitch のバグだと思います。

**Comment by shun159** [comment]
readonlyっぽい挙動ですね。

あまり関係はないですが、ちょっとした連携ですが、
flow_statsとaggreagate_statsは0xfeの情報を取ることはできます。
このテーブル、内部で利用されているっぽくて、もし、flow_statsをとりたくなったときは、
nxmのrecirc_id、reg0をサポートする必要あります。

**Comment by yasuhito** [comment]
@shun159 すみません、もういっこ追加質問です。いまのソースコードでは、テーブルID=0に次の2つのフローエントリを指定しています。気になってるのは、どちらも優先度が 2 になってることです。

1. IPマルチキャストフレームをdrop (優先度=2)
2. それ以外は goto table 1 (優先度=2)

最初に 1. をやったあと、残ったやつを 2. にひっかけたいはずなので、2. の優先度はひょっとして 1 が正しいでしょうか?

**Comment by shun159** [comment]
です。これは実は先に気づいてたのですが、直すのを忘れてしまっていました…。

**Comment by yasuhito** [comment]
わかりましたありがとうございます!

**Comment by shun159** [comment]
> 1.3.4 の仕様には OFPTT_MAX まで使ってよい、と書いてあるのでやはり vswitch のバグだと思います。

これについていろいろ聞いて回ったり、調べたりしてたのですが、
とりあえずOVS特有の問題っぽい感じでした。失礼しました。

**Comment by yasuhito** [comment]
3 番目の件は #186 に移動しました。
