### ISSUE TITLE
Match.new(ether_destination_address: message.source_mac)

### ISSUE THREAD

**Issue by yasuhito** [yasuhito/trema-book#106]
下のように、MACアドレスがマッチだと `ether_*_address` となっているけど、`PacketIn` だと `*_mac` になっているので、どちらかに統一したい。

```ruby
Match.new(ether_destination_address: message.source_mac)
```

みなさんはどちらが良いと思いますか? (それとも、両方サポートしたほうがいい?)

**Comment by otahi** [comment]
私はMACアドレスのマッチを見ているのであれば、`*_mac`のほうがよいと思います。
Wifiとかもあるので、`ether_*_address` だと十分ではないように思います。

**Comment by yasuhito** [comment]
ありがとうございます!
> Wifiとかもあるので、ether_*_address だと十分ではないように思います。
Wifi のことがよく分かってなくてもうしわけないんですが、Wifiだとどういうことになりますか?

**Comment by otahi** [comment]
単純に無線LANはEthernetではない と思いますので、Ethernetだけが対象なのか とかそういった疑問がでるのかな という意味です。

**Comment by yasuhito** [comment]
あっわかりました! では、単純に `*_mac` のほうにもろもろ統一したいと思います。
