### ISSUE TITLE
12. NFVを作ろう: ルータ (前編)へのコメント

### ISSUE THREAD

**Issue by otahi** [yasuhito/trema-book#119]
本質的なところではありませんが、いくつか気になったところがありましたので、
コメントします。(単純に修正できないので、Issueとしました。)

1. イーサネット以外のパケット転送方式に無線LANを追加するのがよいと思います。
https://github.com/yasuhito/trema-book/blame/8106bfcaa40f116d6989928c03145d48985ae476/router_part1.adoc#L17

  - たとえば1つ例を追加する
    - ノートパソコンやタブレットやスマートフォンでよく使う無線LAN。いまではなくてはならない

2. 無線LANでもMACアドレスがあります。どこかで、イーサネットと無線LANは区別して考えないという説明をしてあげる必要があるように思います。(くどくなるかもしれないので、不要かもしれません。)
https://github.com/yasuhito/trema-book/blame/8106bfcaa40f116d6989928c03145d48985ae476/router_part1.adoc#L25

  - 脚注で、イーサネットと無線LANの違いについては、ここでは区別しない 旨があれば十分かもしれません。  

3. 途中からはATM, PPPなどについては触れないので、一般的なイーサネットの利用を前提に説明する旨があったほうがよいかもしれません。
https://github.com/yasuhito/trema-book/blame/8106bfcaa40f116d6989928c03145d48985ae476/router_part1.adoc#L34

4. 「 `forward` メソッド内の変数 `action` はこのための」の`action`は`actions` だと思います。
https://github.com/yasuhito/trema-book/blame/8106bfcaa40f116d6989928c03145d48985ae476/router_part1.adoc#L192

**Comment by yasuhito** [comment]
@otahi コメントありがとうございます! e968529a7b6a951f32160da3b2a3be16b76a215e で修正を入れてみたので、確認をおねがいします〜。

**Comment by otahi** [comment]
@yasuhito  ありがとうございます！
2016/01/07中には、 e968529 を確認します。

**Comment by otahi** [comment]
@yasuhito 確認しました。問題ありません。
対応ありがとうございました！
