### ISSUE TITLE
1.4.4 章に関して

### ISSUE THREAD

**Issue by kazuyas** [yasuhito/trema-book#129]
前の Issue で NFV と OpenFlow (制御・転送分離) は別の概念であると指摘しましたが、その前提で書きます。

まず、ここに書かれていることは NFV の特徴であり、OpenFlow の特徴ではありません。OpenFlow の場合で考えてみると、転送と制御が分かれているので、それぞれで負荷上昇に対して、スケールしやすいかを考えてみる必要があるのですが、ここはその辺の話がごっちゃになっているようで読めませんでした。

コントローラに関しては、確かにソフトウェアなのでスケールアウト可能かもしれませんが、内部状態の同期に関する議論抜きには語れません。(それを頑張っているのが ONOS ですが)

転送系に関しては、トラフィックが特定の箇所に集中しないように制御が可能ですが、それをどう実現するか語らないとだめだと思います。

いずれにしろ OpenFlow ならば可能かもしれないが、実現するための方法を考える必要があるということになります。なので、OpenFlow の一般的な特徴というには難しく、かつこの分量でまとめきれる内容ではないかと思います。

**Comment by yasuhito** [comment]
そのとおりで OpenFlow と NFV は違うモノですが、もしちゃんと正しく書くなら「NFV の実現方法として OpenFlow を使う場合もある」と書くのがよいでしょうか。

実現方法がむずかしいのもそのとおりだと思います。ただしょっぱなの第 1 章だけですべてを議論するのはいきなりムズすぎなので、細かい実現方法については各章を見てね、という書き方になっています。

それぞれの章で、回収しないといけないので大変ですが。。。そのへんをがんばってるのが ONOS ですとか、そういうコラムを入れればいいのかなあ??

個人的にはこの章は 1 章なので、なるべく読み進めたくなるような NFV とかのいけてるキーワードを入れときたい && 全体のガイドとしてざっと簡単に読めるようにしておきたい、と思っています。

**Comment by yasuhito** [comment]
1章から NFV を削り、スケールアウトの議論を加えたので閉じます。
