### ISSUE TITLE
ラーニングスイッチ章: ”スイッチのバッファを使ってPacket Outする場合” 中の記述について

### ISSUE THREAD

**Issue by kazuyas** [yasuhito/trema-book#146]
”ただし、第4章のコラムで説明したとお り、バッファの中身は予測不能でデータがいつ消えるかわからないため、この方法 は推奨しません。”

という記述がありますが、4 章には説明がないようです。確認してください。

**Comment by yasuhito** [comment]
@kazuyas OpenFlow章にもともとあったコラム「Flow ModとPacket Outを同時にやる方法？」が消えているようなので、復活しておいてもらえますか? ラーニングスイッチ章からはそちらを参照するようにします。

**Comment by yasuhito** [comment]
#177 で「Flow ModとPacket Outを同時にやる方法？」コラムを復活しました。

**Comment by yasuhito** [comment]
78e88c9832aede20645d419766ee69e44a1afd9f で修正しました。
