### ISSUE TITLE
ラーニングスイッチ1.3章: Figure 7.3. WriteActions でアクションを後でまとめて適用

### ISSUE THREAD

**Issue by kazuyas** [yasuhito/trema-book#147]
アクションセット中のアクションの適用が、ID=2 のテーブル中にありますが、外出しのほうがよいかと思います。

あと、Goto-Table を含まないエントリにマッチした時に実行とありますが、Goto-Table 先のテーブルでマッチするエントリがない場合でも実行される可能性があります。なので、ここでの表記は正確ではないと思われます。
(仕様を読み込めていないので、不正確かもしれません。仕様中に Goto-Table を含まないエントリにマッチした時うんぬんの記述があるならごめんなさい)

**Comment by yasuhito** [comment]
図のコメントありがとうございます。修正しました。

アクションセットの適用タイミングについて調べてみました。OpenFlow 1.3.4 のスペックを見ると、アクションセットを適用するタイミングはやはり Goto-Table を含まないエントリにマッチしたときのようです。

5.10
> An action set is associated with each packet. This set is empty by default. A flow entry can modify the action set using a Write-Action instruction or a Clear-Action instruction associated with a particular match. The action set is carried between flow tables. When the instruction set of a flow entry does not contain a Goto-Table instruction, pipeline processing stops and the actions in the action set of the packet are executed.

もしマッチしなかった場合、たとえば table-miss フローエントリ (catch-all なフローエントリ。プライオリティ 0 ですべてにマッチする) すらない場合には、アクションセットは実行せずに drop するようです。

5.1
> There are few cases where a packet is not fully processed by a flow entry and pipeline processing stops without processing the packet’s action set or directing it to another table. If no table-miss flow entry is present, the packet is dropped (see 5.4).
