### ISSUE TITLE
ラーニングスイッチ1.3章: ソースコードに関して

### ISSUE THREAD

**Issue by kazuyas** [yasuhito/trema-book#148]
OF1.3 版のコントローラで、マルチキャストとブロードキャスト落としているけど、これだと ARP 通らないから、使いものにならないのでは？

**Comment by kazuyas** [comment]
上位 8 ビットだけマスクしているのか...

**Comment by kazuyas** [comment]
IP マルチキャストだけ落としたいということを説明して、
01-00-5E-00-00-00 の上位 25 bit をマスクするとしたほうが意図はわかりやすいかと思います。

**Comment by kazuyas** [comment]
ちなみにマルチキャスト落としちゃうと、MAC だと Bonjour とかが動かなくなります。

**Comment by yasuhito** [comment]
@kazuyas ありがとうざいます。 610f133 で、01-00-5E-00-00-00 の上位 25 bit をマスクするように修正しました。

ところで、やっぱりマルチキャストは落とさないほうがいいでしょうか? マルチキャストフレームを送る人も宛先になりうるので、FDB に学習したほうがいい気がしています。

**Comment by shun159** [comment]
@yasuhito 

ちなみに
> ところで、やっぱりマルチキャストは落とさないほうがいいでしょうか? 

もともとは、of1.0版をof1.3で書きなおしたもので、of1.3ではmulticastをスイッチでdropするようにしていました。

> マルチキャストフレームを送る人も宛先になりうるので、FDB に学習したほうがいい気がしています。

もし必要でしたらそのように修正をします。(学習はするが、dropする。もしくは、学習し、かつfloodする。とか）
たしかどなたかがマルチキャストはdropしますよ、と以前おっしゃっていたと思いますが、
他のアプリのマルチキャストの扱いに関するフローテーブルとか読むとfloodするようになっている
ものもあるようですね。

**Comment by yasuhito** [comment]
@shun159 コメントありがとうございます!

ラーニングスイッチ1.3章の主題を振り返っておきますと、この章で説明したいのはマルチプルテーブル + GotoTableで、いまはこの 2 個になっています。

* フィルタリング用テーブル (ID=0)
  * 現状でエントリはマルチキャスト (IPv4, IPv6) の 2 つ
* フォワーディング用テーブル (ID=1)

もしマルチキャストをフィルタリングしないとなると、テーブル ID=0 がなくなってしまうので、何かしらフィルタリングはしておきたいのですが、マルチキャスト以外に妥当なフィルタリング候補は思い付きますか?

**Comment by shun159** [comment]
@yasuhito 他にはおもいつきません…。単にvlan tagされてるフレーム落とすとか…？
`vlan_tci=1000/1000 ... actions=drop` のように。すいません。

**Comment by yasuhito** [comment]
@shun159 ありがとうございます。やっぱりマルチキャストをフィルタリングするのかな。。。。鈴木さんが今席をはずしてるので、帰ってきたら聞いてみます!

**Comment by shun159** [comment]
へい！

**Comment by yasuhito** [comment]
@shun159 すこし話がそれますが、"学習するけど drop"ってできますか? 学習するなら Packet In は起こっちゃう気がしています。

**Comment by yasuhito** [comment]
ああ、学習したあと src_mac ごとに drop のエントリを入れるという話かな? だったら分かります!

**Comment by shun159** [comment]
> @shun159 すこし話がそれますが、"学習するけど drop"ってできますか? 学習するなら Packet In は起こっちゃう気がしています。

はい、"学習するけど drop”の場合なら、packet_inが入ります。
多分したのように書くのだとおもいますが、Tremaにはあまりpacket_in上げたくないな…とおもってます。
```
priority=2 table=0 dl_dst=multicast actions=controller
priority=1 table=0 any actions=goto_table(forwarding)
```

```ruby
def packet_in(dpid, packet_in)
  @fdb.learn(packet_in)
  return if packet_in.dst_mac.reserved?
  #....
end
```

ちなみにlearning_switch13の実装また更新するとマズいですか？？

**Comment by yasuhito** [comment]
@shun159 実装を更新してもらうのは、全然OKですよ!

**Comment by shun159** [comment]
@yasuhito ありがとうございます！

**Comment by yasuhito** [comment]
最終的に、STPのBPDUをフィルタして落とすようにしました。
