### ISSUE TITLE
ラーニングスイッチ1.3章: 冒頭の OF1.0 の問題点に関して

### ISSUE THREAD

**Issue by kazuyas** [yasuhito/trema-book#149]
フローテーブルが煩雑になる説明に関して
フィルタリング用やパケット転送用のエントリがあると書かれていますが、そのような説明は前章にはありませんでした。

PacketInが防げない
OF1.3 でも完全にPacketInをなくしているわけではないので、どのようなPacketInを減らしているのかを説明したほうがよいと思います。主にマルチキャストということでしょうが。

マルチキャストを落とすという説明は、ユーザ側ではなく、OpenFlow コントローラを作る側の都合のような気がします。あまり例としてはよろしくないような。。。

**Comment by yasuhito** [comment]
- 前の章にフィルタリング用のフローエントリの説明を追加しました
- どんなフィルタリングをするかの説明を追加しました
