### ISSUE TITLE
ルータ前編 : 無線LANの説明を削除する

### ISSUE THREAD

**Issue by kazuyas** [yasuhito/trema-book#165]
実は、ハードウェアに近いパケット転送方式はイーサネット以外にもいくつもあり ます。イーサネットは、転送方式のうちのたった 1 つにすぎないのです。
• スマートフォンやノートパソコンで使う無線 LAN。今ではなくてはならないもの のひとつ

という記述がありますが、無線LANもイーサネットの一種です。ここで説明している MAC アドレスを学習して転送するという点に関して、違いはありません。
ここで比較すべきではないので、この例は削除すべきです。

**Comment by otahi** [comment]
@kazuyas この記載は#119 で私が提案したものでした。
無線LANがethernetに含まれない想定で追記していました。
ルーティングという意味では違いはないのですが、無線LANが含まれていることがわかるようになっているとよいと思っていました。

**Comment by kazuyas** [comment]
otahi さん、コメントありがとうございます。
たしかに無線LAN自体は身近なもので記述はあった方がよいかと思いますので、別の場所に記述を残したいと思っています。

**Comment by yasuhito** [comment]
@kazuyas いまルータ章を見直していますが、このチケットどうしましょうか?

**Comment by yasuhito** [comment]
@otahi すみません、無線 LAN の説明をうまく本文になじませられなかったため、最終的に本文からはずしました。

**Comment by otahi** [comment]
@yasuhito @kazuyas いろいろご検討いただきありがとうございました。
注文済みの本が手元に届くのを楽しみにしています。
