### ISSUE TITLE
TremaでOpenFlowプログラミング書籍通りに行うとエラーが発生。

### ISSUE THREAD

**Issue by xfarm001** [yasuhito/trema-book#199]
私の勘違いでしたら申し訳ございません。
下記内容にて実行したところエラーが発生してしまいます。
動画を載せましたのでご確認頂けましたら幸いです。

動画URL
https://www.youtube.com/watch?v=c5Q1S-Biq2E&feature=youtu.be

手順
1. yum install ruby ruby-devel gcc gcc-c++
1. gem install bundler
1. yum install https://rdoproject.org/repos/rdo-release.rpm
1. sudo yum install openvswitch
1. sudo systemctl start openvswitch.service
1. mkdir -p hello_trema/lib
2. cd hello_trema
3. lib/hello_trema.rb に下記内容
   # Hello World!
   class HelloTrema < Trema::Controller
   def start(_args)
     logger.info 'Trema started.'
   end
   
   def switch_ready(datapath_id)
     logger.info "Hello #{datapath_id.to_hex}!"
   end
   end
4. trema.confに下記内容
   vswitch { datapath_id 0xabc }
5. Gemfileに下記内容
   source 'https://rubygems.org/'
   gem 'trema'
6. bundle install --binstubs
7. ./bin/trema --version

**Comment by otahi** [comment]
@xfarm001 CentOS7の環境でのインストールのようですね。(動画より、文字のログのほうが助かります。。)

私もvagrant の環境で再現してみました。

```
[vagrant@localhost hello_trema]$ ./bin/trema --version
/home/vagrant/hello_trema/vendor/bundle/ruby/gems/trema-0.10.0/bin/trema:8:in `require': cannot load such file -- rake (LoadError)
        from /home/vagrant/hello_trema/vendor/bundle/ruby/gems/trema-0.10.0/bin/trema:8:in `<top (required)>'
        from ./bin/trema:16:in `load'
        from ./bin/trema:16:in `<main>'
[vagrant@localhost hello_trema]$
```

とりあえず回避するためには、Gemfileを以下のようにrakeを追加すればよさそうです。

``` ruby
source 'https://rubygems.org/'
gem 'trema'
gem 'rake'
```

```
[vagrant@localhost hello_trema]$ ./bin/trema --version
trema version 0.10.0
[vagrant@localhost hello_trema]$ 
```

@yasuhito 
次のcommitでrakeがなくなっていることによるものという気がします。
タイミングとしては、書籍のCentOS7でインストールする部分を記載したあとにgemspecを修正しているようです。
https://github.com/trema/trema/commit/77710c13420d48dbafb82cb2678c302f95b0a584#diff-ec37e9b07699c2997ab8ff85f6515843

**Comment by xfarm001** [comment]
# ありがとうございます！

**Comment by yasuhito** [comment]
@xfarm001 文字がでかいですね 笑。レポートありがとうございます。
@otahi 検証助かります! いま Trema のほうを直してみます。

**Comment by yasuhito** [comment]
@xfarm001  Trema のほうを直しておきました。これで、Gemfile に gem 'rake' を入れなくても動くはずです。
