### ISSUE TITLE
【誤字】さざまなな⇒さまざまな

### ISSUE THREAD

**Issue by shimi7o** [yasuhito/trema-book#201]
誤字だと思われる箇所がありました。

1.6 まとめ
・自動化やさざまななシステムとの連携
⇒　・自動化やさまざまなシステムとの連携

さまざまなは漢字でもよいかと思います。

**Comment by yasuhito** [comment]
@shimmy0619  誤字の指摘ありがとうございます! ぜひプルリクエストおねがいします。
なお「さまざま」は技術評論社のルールに合わせていますので、ひらがなのままでお願いします。

**Comment by shimi7o** [comment]
リポジトリに修正したローカルブランチをpushできません。権限がないような気がするのですが。

```
$git push origin typo
remote: Permisson to yasuhito/trema-book.git denied to shimmy0619.
fatal:  unable to access 'https://github.com/yasuhito/trema-book.git/': The requested URL returned error: 403
```

**Comment by yasuhito** [comment]
@shimmy0619 権限のないリポジトリにプルリクエストを送るときは、まず trema-book を fork しプルリクエスト用のブランチを作り、そこに push する形になります。
