### ISSUE TITLE
「この情報を活かし」「この情報を生かし」どっちがよい?

### ISSUE THREAD

**Issue by yasuhito** [yasuhito/trema-book#52]
参照: https://github.com/yasuhito/trema-book/issues/50#issuecomment-139929996

**Comment by stereocat** [comment]
これはこちらもあげるかどうするか迷ったんですが、単純に「活用して」で置き換えられるかなあと思ったので「活かす」かなと思ってあげています。でも「いかす」で辞書引くと「生かす/活かす」で出てくるので「生かす」でも大丈夫だと思います。

**Comment by yasuhito** [comment]
活かしにしてみました!
